### ISSUE TITLE
OoT: Scarecrow can softlock if mashing A

### ISSUE THREAD

**Issue by Nax** [OoTMM/core#58]

**Comment by adaliaramon** [comment]
Not sure if you were referring to this, but I have found that just talking to the scarecrow in Lake Hylia puts it in an eternal dance, using the latest `develop` branch

**Comment by Revvenn** [comment]
While you're fixing this, it might be a good idea to just delete that other scarecrow in Lake Hylia, the one above Pierre. OOTR did that due to some new/casual players trying to get Scarecrow Song from him instead and then running into issues (not sure if the same issues exist here) so to be safe in the future might be worth just deleting that second scarecrow entirely.

**Comment by Nax** [comment]
Fixed
